In [14]:
import pandas as pd
import numpy as np

google_trends = pd.read_csv("../data/gold_google_trends_daily.csv")
data = pd.read_csv("../files/processed_data.csv")

In [15]:
# data.drop(["away_team_code", "kickoff_time_local", "match_id", "weekday", "date", "ohl_interest"], axis=1).corr()
data

,away_team_code,last_result_vs_opponent,kickoff_time_local,tickets_scanned,match_id,weekday,date,ohl_interest
0,WES,0,18:15:00,5565.0,d256yo3eng04m0fu7b4sl7wno,5,2022-07-30,17.32
1,CLU,-3,18:30:00,7440.0,d4mn5ksbxuvnaww4pmommxhqs,6,2022-08-14,30.38
2,KVO,2,18:15:00,4489.0,d65hmi7sq03yzr5he1k7ypus4,5,2022-08-27,22.18
3,CHA,3,20:45:00,4508.0,d80mkemezkz16bqh6lbn8tlhw,5,2022-09-10,19.08
4,STG,-3,16:00:00,6290.0,dak40etbhbqsr1nxyt50qcg0k,5,2022-10-01,17.75
...,...,...,...,...,...,...,...,...
66,CER,1,19:15:00,5812.0,ecz9iyxyc5ira9n59m8cp3bis,6,2025-12-21,34.16
67,STG,-5,20:45:00,5322.0,enw1n6mhkzvb6uptwhzs4gowk,5,2026-01-24,47.30
68,KVM,0,19:15:00,5971.0,eqncupz92qy89z9bxks1e0t90,6,2026-02-01,40.00
69,DEN,1,16:00:00,5137.0,ewgb5fczpfa71pfzihlip6yok,5,2026-02-14,40.00
70,WES,-2,16:00:00,6062.0,rf7k8o1xjf0xw5zrgpbtmhg,5,2026-03-07,53.00

In [16]:
data["date"] = pd.to_datetime(data["date"])
data["month"] = data['date'].dt.month

data['month_sin'] = np.sin(2 * np.pi * data['month'] / 12)
data['month_cos'] = np.cos(2 * np.pi * data['month'] / 12)
data = data.drop(["month"], axis=1)

In [17]:
data["kickoff_time_local"] = pd.to_datetime(data["kickoff_time_local"], format='%H:%M:%S')

In [18]:
data['kickoff_time_local'] = pd.to_datetime(data['kickoff_time_local']).dt.hour

data = pd.get_dummies(data, columns=['kickoff_time_local'])

In [19]:
data["is_sunday"] = data["weekday"] == 6
data["is_saturday"] = data["weekday"] == 5
data["is_friday"] = data["weekday"] == 4
data["is_fri_hol"] = data["weekday"].isin([4, 5, 6])
data["is_mon"] = data["weekday"] == 0
data["is_tue"] = data["weekday"] == 1
data["is_wed"] = data["weekday"] == 2
data["is_thu"] = data["weekday"] == 3

In [20]:
data.drop(["away_team_code", "match_id", "date", "ohl_interest"], axis=1).corr()

,last_result_vs_opponent,tickets_scanned,weekday,month_sin,month_cos,kickoff_time_local_16,kickoff_time_local_18,kickoff_time_local_19,kickoff_time_local_20,kickoff_time_local_21,is_sunday,is_saturday,is_friday,is_fri_hol,is_mon,is_tue,is_wed,is_thu
last_result_vs_opponent,1.000000,-0.096938,0.071193,-0.026779,-0.223162,-0.014308,0.002798,-0.057342,0.011616,0.166578,-0.157052,0.272813,-0.065939,0.174325,NaN,-0.141300,-0.099198,NaN
tickets_scanned,-0.096938,1.000000,0.153500,-0.042470,0.152736,-0.048723,0.314116,-0.179159,-0.108898,-0.186673,0.164812,-0.071704,-0.102380,0.047290,NaN,-0.099776,0.059364,NaN
weekday,0.071193,0.153500,1.000000,-0.043070,-0.117604,0.140103,-0.095435,0.327015,-0.344267,0.102587,0.692608,-0.080303,-0.423538,0.753047,NaN,-0.664425,-0.352644,NaN
month_sin,-0.026779,-0.042470,-0.043070,1.000000,0.020825,0.072459,0.042730,0.041629,-0.187525,0.076192,-0.022158,0.041736,-0.079082,-0.088100,NaN,0.052850,0.076192,NaN
month_cos,-0.223162,0.152736,-0.117604,0.020825,1.000000,-0.037199,0.022702,0.174803,-0.164609,0.131535,0.097530,-0.173414,-0.033242,-0.246360,NaN,0.205853,0.131535,NaN
kickoff_time_local_16,-0.014308,-0.048723,0.140103,0.072459,-0.037199,1.000000,-0.478817,-0.255293,-0.346789,-0.080087,0.144831,0.043422,-0.271299,-0.010662,NaN,0.070003,-0.080087,NaN
kickoff_time_local_18,0.002798,0.314116,-0.095435,0.042730,0.022702,-0.478817,1.000000,-0.272259,-0.369835,-0.085410,-0.150166,0.232618,-0.203736,-0.145925,NaN,0.058295,0.167261,NaN
kickoff_time_local_19,-0.057342,-0.179159,0.327015,0.041629,0.174803,-0.255293,-0.272259,1.000000,-0.197186,-0.045538,0.472151,-0.325907,-0.154263,0.080026,NaN,-0.064866,-0.045538,NaN
kickoff_time_local_20,0.011616,-0.108898,-0.344267,-0.187525,-0.164609,-0.346789,-0.369835,-0.197186,1.000000,-0.061859,-0.417635,-0.023611,0.683131,0.108707,NaN,-0.088113,-0.061859,NaN
kickoff_time_local_21,0.166578,-0.186673,0.102587,0.076192,0.131535,-0.080087,-0.085410,-0.045538,-0.061859,1.000000,0.148117,-0.102240,-0.048393,0.025105,NaN,-0.020349,-0.014286,NaN
is_sunday,-0.157052,0.164812,0.692608,-0.022158,0.097530,0.144831,-0.150166,0.472151,-0.417635,0.148117,1.000000,-0.690261,-0.326723,0.169493,NaN,-0.137384,-0.096449,NaN
is_saturday,0.272813,-0.071704,-0.080303,0.041736,-0.173414,0.043422,0.232618,-0.325907,-0.023611,-0.102240,-0.690261,1.000000,-0.346341,0.179670,NaN,-0.145633,-0.102240,NaN
is_friday,-0.065939,-0.102380,-0.423538,-0.079082,-0.033242,-0.271299,-0.203736,-0.154263,0.683131,-0.048393,-0.326723,-0.346341,1.000000,0.085044,NaN,-0.068933,-0.048393,NaN
is_fri_hol,0.174325,0.047290,0.753047,-0.088100,-0.246360,-0.010662,-0.145925,0.080026,0.108707,0.025105,0.169493,0.179670,0.085044,1.000000,NaN,-0.810558,-0.569043,NaN
is_mon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_tue,-0.141300,-0.099776,-0.664425,0.052850,0.205853,0.070003,0.058295,-0.064866,-0.088113,-0.020349,-0.137384,-0.145633,-0.068933,-0.810558,NaN,1.000000,-0.020349,NaN
is_wed,-0.099198,0.059364,-0.352644,0.076192,0.131535,-0.080087,0.167261,-0.045538,-0.061859,-0.014286,-0.096449,-0.102240,-0.048393,-0.569043,NaN,-0.020349,1.000000,NaN
is_thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN